lines <- c(
  '---',
  'title: "BioClockR Phase 4 - Gene Expression Aging Validation"',
  'author: "Naresh Gumala"',
  'output: html_document',
  '---',
  '',
  '```{r setup, include=FALSE}',
  'knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)',
  'library(dplyr)',
  'library(ggplot2)',
  'library(tidyr)',
  'nhanes_model <- readRDS("C:/Users/Naresh Gumala/Documents/GitHub/BioClockR/data-raw/model_output/nhanes_model.rds")',
  'nhanes_model <- nhanes_model %>%',
  '  mutate(',
  '    inflammaging_score = scale(crp_log)[,1] + scale(wbc)[,1],',
  '    metabolic_score    = scale(glucose)[,1] + scale(rdw)[,1],',
  '    aging_score        = inflammaging_score + metabolic_score',
  '  )',
  '```',
  '',
  '## 1. Inflammaging Score vs Age Acceleration',
  '',
  '```{r inflammaging, echo=FALSE}',
  'ggplot(nhanes_model, aes(x = inflammaging_score, y = age_accel)) +',
  '  geom_point(alpha = 0.15, color = "steelblue") +',
  '  geom_smooth(method = "lm", color = "red", se = TRUE) +',
  '  labs(title = "Inflammaging Score vs Biological Age Acceleration",',
  '       subtitle = "CRP and WBC as proxies for TNF-alpha/IL-6 pathway activity",',
  '       x = "Inflammaging Score (standardized)",',
  '       y = "Age Acceleration (years)") +',
  '  theme_minimal()',
  '```',
  '',
  '## 2. Metabolic Aging Score vs Age Acceleration',
  '',
  '```{r metabolic, echo=FALSE}',
  'ggplot(nhanes_model, aes(x = metabolic_score, y = age_accel)) +',
  '  geom_point(alpha = 0.15, color = "darkorange") +',
  '  geom_smooth(method = "lm", color = "red", se = TRUE) +',
  '  labs(title = "Metabolic Aging Score vs Biological Age Acceleration",',
  '       subtitle = "Glucose and RDW as proxies for metabolic stress pathways",',
  '       x = "Metabolic Score (standardized)",',
  '       y = "Age Acceleration (years)") +',
  '  theme_minimal()',
  '```',
  '',
  '## 3. Combined Aging Score by Race',
  '',
  '```{r aging_race, echo=FALSE}',
  'nhanes_model %>%',
  '  mutate(race = as.character(race)) %>%',
  '  ggplot(aes(x = reorder(race, aging_score, median), y = aging_score, fill = race)) +',
  '  geom_boxplot(alpha = 0.7) +',
  '  coord_flip() +',
  '  labs(title = "Combined Aging Score by Race/Ethnicity",',
  '       x = "Race/Ethnicity", y = "Aging Score") +',
  '  theme_minimal() + theme(legend.position = "none")',
  '```',
  '',
  '## 4. Pathway Correlations',
  '',
  '```{r correlations, echo=FALSE}',
  'nhanes_model %>%',
  '  select(age_accel, inflammaging_score, metabolic_score, aging_score) %>%',
  '  cor(use = "complete.obs") %>%',
  '  round(3)',
  '```',
  '',
  '## 5. Aging Score vs Biological Age by Sex',
  '',
  '```{r aging_bio, echo=FALSE}',
  'ggplot(nhanes_model, aes(x = aging_score, y = bio_age, color = sex)) +',
  '  geom_point(alpha = 0.15) +',
  '  geom_smooth(method = "lm", se = FALSE) +',
  '  labs(title = "Combined Aging Score vs Biological Age",',
  '       x = "Aging Score", y = "Biological Age (years)") +',
  '  theme_minimal()',
  '```'
)

writeLines(lines, "analysis/phase4_geo_validation.Rmd")
message("Done")

